export const dentalInsuranceList = [
  {
    id: "Access Plans USA (AKAAon Benefit Solutions)",
    label: "Access Plans USA (AKAAon Benefit Solutions)",
  },
  {
    id: "Access One Consumer Health, Inc",
    label: "Access One Consumer Health, Inc",
  },
  { id: "ACS Benefit Services LLC", label: "ACS Benefit Services LLC" },
  {
    id: "Actuarial Management Resources, Inc",
    label: "Actuarial Management Resources, Inc",
  },
  { id: "Admin/Dental Pay", label: "Admin/Dental Pay" },
  {
    id: "Administration Services Only (ASO)",
    label: "Administration Services Only (ASO)",
  },
  {
    id: "Administration Systems Research Corp",
    label: "Administration Systems Research Corp",
  },
  { id: "Administrative Concepts, Inc", label: "Administrative Concepts, Inc" },
  {
    id: "Administrative Solutions, Inc",
    label: "Administrative Solutions, Inc",
  },
  { id: "ADN Administrators, Inc.", label: "ADN Administrators, Inc." },
  {
    id: "Advantica (FKA Essex Dental Benefits)",
    label: "Advantica (FKA Essex Dental Benefits)",
  },
  { id: "AFSCME Care Plan of Ohio", label: "AFSCME Care Plan of Ohio" },
  { id: "Aetna PPO/DMO", label: "Aetna PPO/DMO" },
  { id: "Aliera Healthcare Inc", label: "Aliera Healthcare Inc" },
  { id: "Allied Benefit System Inc", label: "Allied Benefit System Inc" },
  {
    id: "AlwaysCare Benefits/Unum/Starmount",
    label: "AlwaysCare Benefits/Unum/Starmount",
  },
  { id: "Ameraplan", label: "Ameraplan" },
  { id: "Amerihealth", label: "Amerihealth" },
  { id: "Amerigroup", label: "Amerigroup" },
  {
    id: "American Dental Professional Services",
    label: "American Dental Professional Services",
  },
  {
    id: "American Sterling Dental Health Plan Inc.",
    label: "American Sterling Dental Health Plan Inc.",
  },
  {
    id: "Ameritas Life Insurance Corp. - Group Div",
    label: "Ameritas Life Insurance Corp. - Group Div",
  },
  {
    id: "Anthem Blue Cross & Blue Shield",
    label: "Anthem Blue Cross & Blue Shield",
  },
  { id: "Apex Benefits Services, LLC", label: "Apex Benefits Services, LLC" },
  { id: "Argus Dental Plans", label: "Argus Dental Plans" },
  {
    id: "Assured Benefits Administrators, Inc.",
    label: "Assured Benefits Administrators, Inc.",
  },
  { id: "Assurant PPO", label: "Assurant PPO" },
  { id: "Aultra Administrative Group", label: "Aultra Administrative Group" },
  { id: "Automated Benefit Services", label: "Automated Benefit Services" },
  { id: "Avalon Benefit Services, Inc", label: "Avalon Benefit Services, Inc" },
  { id: "Avesis Incorporated", label: "Avesis Incorporated" },
  { id: "Avesis Medicaid", label: "Avesis Medicaid" },
  { id: "Beam Dental", label: "Beam Dental" },
  { id: "Ben-E-Lect", label: "Ben-E-Lect" },
  {
    id: "Benefit Administrative Solutions, Inc-aka HUM Int",
    label: "Benefit Administrative Solutions, Inc-aka HUM Int",
  },
  {
    id: "Benefit Administrative Systems, LLC",
    label: "Benefit Administrative Systems, LLC",
  },
  {
    id: "Benefit Administrators Inc. AK HUB International E",
    label: "Benefit Administrators Inc. AK HUB International E",
  },
  {
    id: "Benefit Assistance Corporation",
    label: "Benefit Assistance Corporation",
  },
  { id: "Benefit Services-New Jersey", label: "Benefit Services-New Jersey" },
  { id: "Benesys Inc.", label: "Benesys Inc." },
  {
    id: "Bento a.k.a. Cambalt Solutions, Inc",
    label: "Bento a.k.a. Cambalt Solutions, Inc",
  },
  { id: "BEST Health Plans", label: "BEST Health Plans" },
  {
    id: "Best Life & Health Insurance Company",
    label: "Best Life & Health Insurance Company",
  },
  { id: "Beta Health Association", label: "Beta Health Association" },
  {
    id: "Blue Cross and Blue Shield of Kansas City",
    label: "Blue Cross and Blue Shield of Kansas City",
  },
  { id: "Blue Cross Blue Shield of AL", label: "Blue Cross Blue Shield of AL" },
  { id: "Blue Cross Blue Shield of AZ", label: "Blue Cross Blue Shield of AZ" },
  {
    id: "Blue Cross Blue Shield of AZ Advantage",
    label: "Blue Cross Blue Shield of AZ Advantage",
  },
  { id: "Blue Cross Blue Shield of MA", label: "Blue Cross Blue Shield of MA" },
  { id: "Blue Cross Blue Shield of MI", label: "Blue Cross Blue Shield of MI" },
  {
    id: "Blue Cross Blue Shield of South Carolina",
    label: "Blue Cross Blue Shield of South Carolina",
  },
  { id: "Blue Cross Blue Shield of TN", label: "Blue Cross Blue Shield of TN" },
  { id: "Blue Cross of Idaho", label: "Blue Cross of Idaho" },
  { id: "Bright Benefits", label: "Bright Benefits" },
  { id: "Brokerage Concepts, Inc.", label: "Brokerage Concepts, Inc." },
  {
    id: "Business Administrators & Consultants",
    label: "Business Administrators & Consultants",
  },
  { id: "Capitol Administrators CA", label: "Capitol Administrators CA" },
  { id: "CareFirst Advantage PPO, Inc", label: "CareFirst Advantage PPO, Inc" },
  { id: "CAREington", label: "CAREington" },
  {
    id: "Central States Health & Life Co.",
    label: "Central States Health & Life Co.",
  },
  {
    id: "Centrix Benefit Administrators, Inc.",
    label: "Centrix Benefit Administrators, Inc.",
  },
  { id: "Century Healthcare", label: "Century Healthcare" },
  { id: "CFA (Formerly NCAS)", label: "CFA (Formerly NCAS)" },
  {
    id: "CIGNA PPO (PAINTERS/FIREFIGHTER AND LOCAL UNION PLAN)",
    label: "CIGNA PPO (PAINTERS/FIREFIGHTER AND LOCAL UNION PLAN)",
  },
  {
    id: "Citizens Security Life Ins. Co",
    label: "Citizens Security Life Ins. Co",
  },
  { id: "CNIC Health Solutions Inc", label: "CNIC Health Solutions Inc" },
  {
    id: "Colonial Life & Accident Insurance Company",
    label: "Colonial Life & Accident Insurance Company",
  },
  { id: "Companion Life-BCBS of SC", label: "Companion Life-BCBS of SC" },
  { id: "CompBenefits-Humana Dental", label: "CompBenefits-Humana Dental" },
  {
    id: "Comprehensive Health Services, Inc",
    label: "Comprehensive Health Services, Inc",
  },
  {
    id: "CoreSource (FKA: FMH Benefit Services, Inc.)",
    label: "CoreSource (FKA: FMH Benefit Services, Inc.)",
  },
  { id: "CoreSource of IL", label: "CoreSource of IL" },
  { id: "CoreSource of MD", label: "CoreSource of MD" },
  { id: "CoreSource of OH", label: "CoreSource of OH" },
  { id: "CoreSource of PA", label: "CoreSource of PA" },
  { id: "Colonial Life/Harrington", label: "Colonial Life/Harrington" },
  { id: "Coverdell", label: "Coverdell" },
  { id: "Custom Design Benefits", label: "Custom Design Benefits" },
  {
    id: "Cypress Dental Administrators",
    label: "Cypress Dental Administrators",
  },
  { id: "DC Medicaid", label: "DC Medicaid" },
  { id: "DeCare International", label: "DeCare International" },
  { id: "Delta Dental PPO", label: "Delta Dental PPO" },
  { id: "Delta Health Systems", label: "Delta Health Systems" },
  { id: "DENCAP Dental Plans, Inc.", label: "DENCAP Dental Plans, Inc." },
  { id: "Dentalplans.com", label: "Dentalplans.com" },
  { id: "DentaQuest", label: "DentaQuest" },
  { id: "DentaQuest ConnectiCare", label: "DentaQuest ConnectiCare" },
  { id: "Dentemax", label: "Dentemax" },
  { id: "Dentist Direct LLC", label: "Dentist Direct LLC" },
  { id: "DFB TPA Services LLC", label: "DFB TPA Services LLC" },
  {
    id: "Dominion Dental Services USA Inc",
    label: "Dominion Dental Services USA Inc",
  },
  {
    id: "EBSO, Inc. AKA 90 Degree Benefits",
    label: "EBSO, Inc. AKA 90 Degree Benefits",
  },
  { id: "Emblem Health/GHI", label: "Emblem Health/GHI" },
  { id: "EMI Health", label: "EMI Health" },
  {
    id: "Employee Benefit Services, Inc",
    label: "Employee Benefit Services, Inc",
  },
  {
    id: "Employee Benefits Administrators, Inc",
    label: "Employee Benefits Administrators, Inc",
  },
  {
    id: "Employee Health Insurance Management, Inc (EHIM)",
    label: "Employee Health Insurance Management, Inc (EHIM)",
  },
  {
    id: "Employee Painters Trust Health & Welfare",
    label: "Employee Painters Trust Health & Welfare",
  },
  { id: "Employee Security Inc.", label: "Employee Security Inc." },
  {
    id: "Employer Driven Insurance Services, Inc",
    label: "Employer Driven Insurance Services, Inc",
  },
  {
    id: "Encore Dental/Stonebridge Life",
    label: "Encore Dental/Stonebridge Life",
  },
  { id: "Enterprise Group Planning", label: "Enterprise Group Planning" },
  { id: "Envolve", label: "Envolve" },
  { id: "EPIC Life Insurance Company", label: "EPIC Life Insurance Company" },
  { id: "Equitable (Formerly AXA)", label: "Equitable (Formerly AXA)" },
  {
    id: "Equitable Financial Life Insurance Company",
    label: "Equitable Financial Life Insurance Company",
  },
  { id: "Excellus", label: "Excellus" },
  { id: "Eye Benefits", label: "Eye Benefits" },
  { id: "FEP BlueDental", label: "FEP BlueDental" },
  {
    id: "Financial Marketing Concept, LTD",
    label: "Financial Marketing Concept, LTD",
  },
  { id: "First Continental Life", label: "First Continental Life" },
  { id: "Florida Combined Life", label: "Florida Combined Life" },
  {
    id: "Florida Health Administrators (FHA-TPA)",
    label: "Florida Health Administrators (FHA-TPA)",
  },
  {
    id: "Flossy a.k.a Grin Technology Services, Inc.",
    label: "Flossy a.k.a Grin Technology Services, Inc.",
  },
  { id: "Free Market Administrators", label: "Free Market Administrators" },
  { id: "Fringe Benefit Group, Inc.", label: "Fringe Benefit Group, Inc." },
  { id: "Geha", label: "Geha" },
  {
    id: "Generali Global Health Services (GGHS)",
    label: "Generali Global Health Services (GGHS)",
  },
  { id: "Global Excel Management", label: "Global Excel Management" },
  { id: "Global Health", label: "Global Health" },
  { id: "Global Managment", label: "Global Managment" },
  {
    id: "Group & Pension Administrators Inc",
    label: "Group & Pension Administrators Inc",
  },
  { id: "Group Administrators Ltd", label: "Group Administrators Ltd" },
  { id: "Group Benefit Services. Inc", label: "Group Benefit Services. Inc" },
  {
    id: "Group Dental Services of Maryland",
    label: "Group Dental Services of Maryland",
  },
  {
    id: "Group Insurance Service Center, INC",
    label: "Group Insurance Service Center, INC",
  },
  {
    id: "Group Management Services (GMS)",
    label: "Group Management Services (GMS)",
  },
  { id: "Group Resources, Inc.", label: "Group Resources, Inc." },
  { id: "HAA Preferred Partners LLC", label: "HAA Preferred Partners LLC" },
  { id: "Harrington/Colonial Life", label: "Harrington/Colonial Life" },
  { id: "Health Design Plus", label: "Health Design Plus" },
  { id: "Health Economics Group Inc", label: "Health Economics Group Inc" },
  {
    id: "Health Partners Dental Administration",
    label: "Health Partners Dental Administration",
  },
  {
    id: "Health Plan Administrators LLC",
    label: "Health Plan Administrators LLC",
  },
  { id: "Healthplex", label: "Healthplex" },
  { id: "HealthEZ", label: "HealthEZ" },
  { id: "Healthgram", label: "Healthgram" },
  { id: "Healthscope Benefits", label: "Healthscope Benefits" },
  { id: "Healthscope Dental", label: "Healthscope Dental" },
  {
    id: "HealthSmart Benefit Solutions - WV",
    label: "HealthSmart Benefit Solutions - WV",
  },
  {
    id: "HealthSmart Benefit Solutions- AZ",
    label: "HealthSmart Benefit Solutions- AZ",
  },
  {
    id: "Healthsmart Benefit Solutions-OH",
    label: "Healthsmart Benefit Solutions-OH",
  },
  {
    id: "HealthSmart-KY-Employee Benefits Administrators In",
    label: "HealthSmart-KY-Employee Benefits Administrators In",
  },
  { id: "Health Markets", label: "Health Markets" },
  { id: "HealthNet Associates", label: "HealthNet Associates" },
  {
    id: "Health Resources/Dental Health Options",
    label: "Health Resources/Dental Health Options",
  },
  { id: "Horizon Blue Cross", label: "Horizon Blue Cross" },
  {
    id: "Humana Dental Insurance Corporation",
    label: "Humana Dental Insurance Corporation",
  },
  { id: "Humana (Zelis)", label: "Humana (Zelis)" },
  { id: "Humana PPO (Nationwide)", label: "Humana PPO (Nationwide)" },
  { id: "INDECS Corporation", label: "INDECS Corporation" },
  { id: "iNetico", label: "iNetico" },
  {
    id: "Insight Benefit Administrators, LLC",
    label: "Insight Benefit Administrators, LLC",
  },
  {
    id: "Insurance Administrators of America",
    label: "Insurance Administrators of America",
  },
  {
    id: "Insurance Design Administrators",
    label: "Insurance Design Administrators",
  },
  {
    id: "Insurance Management Services, Inc (IMS)",
    label: "Insurance Management Services, Inc (IMS)",
  },
  { id: "Interactive Medical Systems", label: "Interactive Medical Systems" },
  {
    id: "International Medical Group Inc.",
    label: "International Medical Group Inc.",
  },
  { id: "J. J. Stanis and Company", label: "J. J. Stanis and Company" },
  { id: "JP Farley", label: "JP Farley" },
  { id: "Key Benefits Administrators", label: "Key Benefits Administrators" },
  {
    id: "Kaiser (for Maryland Medicaid plans with Scion Dental only)",
    label: "Kaiser (for Maryland Medicaid plans with Scion Dental only)",
  },
  { id: "Koegel Meats, Inc.", label: "Koegel Meats, Inc." },
  { id: "Kuwait Cultural Office (KCO)", label: "Kuwait Cultural Office (KCO)" },
  { id: "Level", label: "Level" },
  {
    id: "Level Benefits Inc. DBA Level",
    label: "Level Benefits Inc. DBA Level",
  },
  { id: "Liberty Dental Plan", label: "Liberty Dental Plan" },
  {
    id: "Lifetime Benefit Solutions fka: EBS-RMSCO, Inc.",
    label: "Lifetime Benefit Solutions fka: EBS-RMSCO, Inc.",
  },
  { id: "Lifemap", label: "Lifemap" },
  { id: "Lincoln Financial Group", label: "Lincoln Financial Group" },
  {
    id: "Managed Care of North America",
    label: "Managed Care of North America",
  },
  { id: "MedBen", label: "MedBen" },
  {
    id: "Medical Benefit Administrators of Maryland, Inc",
    label: "Medical Benefit Administrators of Maryland, Inc",
  },
  { id: "Manhattan Life", label: "Manhattan Life" },
  {
    id: "Medical Mutual of Ohio (MMOH)",
    label: "Medical Mutual of Ohio (MMOH)",
  },
  { id: "Medico", label: "Medico" },
  {
    id: "Merchants Benefit Administrators",
    label: "Merchants Benefit Administrators",
  },
  {
    id: "Meritain Health - EV Benefits Mgmt",
    label: "Meritain Health - EV Benefits Mgmt",
  },
  {
    id: "Meritain Health - Minneapolis CBSA Inc.",
    label: "Meritain Health - Minneapolis CBSA Inc.",
  },
  {
    id: "Meritain Health - North American Benefits Network",
    label: "Meritain Health - North American Benefits Network",
  },
  { id: "Meritain Health - Westport", label: "Meritain Health - Westport" },
  { id: "Meritain Health - Weyco", label: "Meritain Health - Weyco" },
  {
    id: "Meritain Health -North American Health Plans",
    label: "Meritain Health -North American Health Plans",
  },
  {
    id: "Meritain Health-Smith Administrators",
    label: "Meritain Health-Smith Administrators",
  },
  { id: "Mid America Associates", label: "Mid America Associates" },
  { id: "Mid-American Benefits Inc", label: "Mid-American Benefits Inc" },
  {
    id: "Morgan White - Standard Life/Am First",
    label: "Morgan White - Standard Life/Am First",
  },
  { id: "Mutual of Omaha", label: "Mutual of Omaha" },
  { id: "MVP Health Care", label: "MVP Health Care" },
  { id: "myBenefits.ai, Inc.", label: "myBenefits.ai, Inc." },
  { id: "National Foundation Life", label: "National Foundation Life" },
  { id: "Nevada Dental Benefits, Ltd", label: "Nevada Dental Benefits, Ltd" },
  { id: "NexDent Dental Plans, Inc", label: "NexDent Dental Plans, Inc" },
  { id: "NGS American", label: "NGS American" },
  {
    id: "Nippon Life Insurance Company of America",
    label: "Nippon Life Insurance Company of America",
  },
  {
    id: "Nova Healthcare Administrators",
    label: "Nova Healthcare Administrators",
  },
  { id: "NovaNet Inc", label: "NovaNet Inc" },
  {
    id: "Ohio Conference of Teamsters Health & Welfare Fund",
    label: "Ohio Conference of Teamsters Health & Welfare Fund",
  },
  {
    id: "Ohio State Plumbers & Pipefitters Health & Welfare",
    label: "Ohio State Plumbers & Pipefitters Health & Welfare",
  },
  { id: "PacificSource Healthplans", label: "PacificSource Healthplans" },
  { id: "Passive PPO", label: "Passive PPO" },
  {
    id: "Patient Provider Alliance, Inc",
    label: "Patient Provider Alliance, Inc",
  },
  {
    id: "Peoples Benefit Life Insurance Company",
    label: "Peoples Benefit Life Insurance Company",
  },
  { id: "Planned Administrators, Inc", label: "Planned Administrators, Inc" },
  {
    id: "Point Comfort Underwriters, Inc",
    label: "Point Comfort Underwriters, Inc",
  },
  { id: "PPO USA Inc.", label: "PPO USA Inc." },
  { id: "Prairie States Enterprises", label: "Prairie States Enterprises" },
  { id: "Preferred Administrators", label: "Preferred Administrators" },
  { id: "Premier Access", label: "Premier Access" },
  { id: "Prime Health Services, Inc", label: "Prime Health Services, Inc" },
  {
    id: "Principal Life Insurance Company",
    label: "Principal Life Insurance Company",
  },
  {
    id: "Printing Specialties/Northwest",
    label: "Printing Specialties/Northwest",
  },
  {
    id: "Priority Health (FKA: CAM Administrative Services)",
    label: "Priority Health (FKA: CAM Administrative Services)",
  },
  { id: "Priority Partners", label: "Priority Partners" },
  { id: "Pro Benefits Administrators", label: "Pro Benefits Administrators" },
  {
    id: "Prodegi Corporate Benefit Services",
    label: "Prodegi Corporate Benefit Services",
  },
  {
    id: "Professional Benefit Administrators, Inc.",
    label: "Professional Benefit Administrators, Inc.",
  },
  {
    id: "Professional Claims Management",
    label: "Professional Claims Management",
  },
  { id: "ProMedical Plan PHC Inc", label: "ProMedical Plan PHC Inc" },
  { id: "Promptous Inc", label: "Promptous Inc" },
  { id: "Redwood Health Services", label: "Redwood Health Services" },
  { id: "Regence Blue Shield", label: "Regence Blue Shield" },
  {
    id: "Regency Employee Benefits Inc.",
    label: "Regency Employee Benefits Inc.",
  },
  { id: "Regional Care, Inc", label: "Regional Care, Inc" },
  { id: "Renaissance Holdings", label: "Renaissance Holdings" },
  { id: "Renaissance", label: "Renaissance" },
  {
    id: "Revolv, Inc. (FKA Corvesta Services, Inc)",
    label: "Revolv, Inc. (FKA Corvesta Services, Inc)",
  },
  { id: "Revolv Corvesta", label: "Revolv Corvesta" },
  { id: "Scion Dental", label: "Scion Dental" },
  { id: "Scion-Kasier", label: "Scion-Kasier" },
  {
    id: "Secure One Benefit Administrator Inc.",
    label: "Secure One Benefit Administrator Inc.",
  },
  {
    id: "Select Benefits Global Marketing Corp.",
    label: "Select Benefits Global Marketing Corp.",
  },
  { id: "Self Funded Plans, Inc", label: "Self Funded Plans, Inc" },
  {
    id: "Self Insured Services Company (Sisco)",
    label: "Self Insured Services Company (Sisco)",
  },
  { id: "Self Insured Services Co.", label: "Self Insured Services Co." },
  {
    id: "Seminole Tribe of Florida Health Plan Administrati",
    label: "Seminole Tribe of Florida Health Plan Administrati",
  },
  { id: "Serventy Insurance Company", label: "Serventy Insurance Company" },
  {
    id: "Shared Health Mississippi, Inc.",
    label: "Shared Health Mississippi, Inc.",
  },
  { id: "Significa Benefit Services", label: "Significa Benefit Services" },
  {
    id: "SKYGEN USA, LLC (FKA: Scion Dental, Inc)",
    label: "SKYGEN USA, LLC (FKA: Scion Dental, Inc)",
  },
  {
    id: "Shelterpoint - Pro Benefits Admin",
    label: "Shelterpoint - Pro Benefits Admin",
  },
  { id: "SISCO", label: "SISCO" },
  {
    id: "Southland Benefit Solutions, LLC",
    label: "Southland Benefit Solutions, LLC",
  },
  { id: "Southwest Preferred Dental", label: "Southwest Preferred Dental" },
  {
    id: "Starmount Life (administered by AlwaysCare Benefit)",
    label: "Starmount Life (administered by AlwaysCare Benefit)",
  },
  { id: "Sun Life Financial", label: "Sun Life Financial" },
  { id: "SureCare Benefits Inc", label: "SureCare Benefits Inc" },
  { id: "Superior Dental Care", label: "Superior Dental Care" },
  { id: "Tall Tree Administrators", label: "Tall Tree Administrators" },
  { id: "The Dental Care Plus Group", label: "The Dental Care Plus Group" },
  {
    id: "The Employee Benefit Service Center",
    label: "The Employee Benefit Service Center",
  },
  {
    id: "The Health Planof the Upper Ohio Valley",
    label: "The Health Planof the Upper Ohio Valley",
  },
  { id: "The Lewer Agency Inc", label: "The Lewer Agency Inc" },
  { id: "The Loomis Company", label: "The Loomis Company" },
  { id: "The Preferred Group.", label: "The Preferred Group." },
  { id: "Trans America", label: "Trans America" },
  { id: "TruAssure Insurance Company", label: "TruAssure Insurance Company" },
  { id: "UFCW (MI)", label: "UFCW (MI)" },
  { id: "UFCW Local 880 H & W Fund", label: "UFCW Local 880 H & W Fund" },
  { id: "UHC Optum Dental", label: "UHC Optum Dental" },
  { id: "Ultra Benefits, Inc", label: "Ultra Benefits, Inc" },
  { id: "UMR", label: "UMR" },
  { id: "UMR Cincinnati", label: "UMR Cincinnati" },
  {
    id: "UMR-Fiserv Health - Benefit Planners, ltd.",
    label: "UMR-Fiserv Health - Benefit Planners, ltd.",
  },
  {
    id: "UMR-Fiserv Health - Harrington Benefit Services",
    label: "UMR-Fiserv Health - Harrington Benefit Services",
  },
  {
    id: "UMR-Fiserv Health - Wausau Benefits Inc.",
    label: "UMR-Fiserv Health - Wausau Benefits Inc.",
  },
  {
    id: "UMR-Midwest Security Administrators",
    label: "UMR-Midwest Security Administrators",
  },
  { id: "Unimerica Dental", label: "Unimerica Dental" },
  { id: "Unified Group Services, Inc", label: "Unified Group Services, Inc" },
  { id: "United Concordia (UCCI)", label: "United Concordia (UCCI)" },
  {
    id: "United Concordia-Tricare (military)",
    label: "United Concordia-Tricare (military)",
  },
  { id: "United Healthcare", label: "United Healthcare" },
  {
    id: "Unum Group (administered by AlwaysCare Benefits)",
    label: "Unum Group (administered by AlwaysCare Benefits)",
  },
  { id: "UPMC Health Plan", label: "UPMC Health Plan" },
  {
    id: "US Health & Life Insurance Company",
    label: "US Health & Life Insurance Company",
  },
  {
    id: "Varipro (Professional Benefit Services)",
    label: "Varipro (Professional Benefit Services)",
  },
  { id: "The VGM Group/HomeLink", label: "The VGM Group/HomeLink" },
  { id: "VitaPlan, LLC", label: "VitaPlan, LLC" },
  { id: "WellCard Health, LLC.", label: "WellCard Health, LLC." },
  { id: "Zelis", label: "Zelis" },
  { id: "Zelis - Cigna", label: "Zelis - Cigna" },
];
