export const timeZoneList = [
  { label: "Etc/GMT+12", value: "Etc/GMT+12" },
  { label: "Pacific/Niue", value: "Pacific/Niue" },
  { label: "Pacific/Honolulu", value: "Pacific/Honolulu" },
  { label: "America/Anchorage", value: "America/Anchorage" },
  { label: "America/Los_Angeles", value: "America/Los_Angeles" },
  { label: "America/Denver", value: "America/Denver" },
  { label: "America/Chicago", value: "America/Chicago" },
  { label: "America/New_York", value: "America/New_York" },
  { label: "America/Puerto_Rico", value: "America/Puerto_Rico" },
  {
    label: "America/Argentina/Buenos_Aires",
    value: "America/Argentina/Buenos_Aires",
  },
  { label: "Atlantic/South_Georgia", value: "Atlantic/South_Georgia" },
  { label: "Etc/UTC", value: "Etc/UTC" },
  { label: "Europe/Berlin", value: "Europe/Berlin" },
  { label: "Europe/Athens", value: "Europe/Athens" },
  { label: "Europe/Moscow", value: "Europe/Moscow" },
  { label: "Asia/Tehran", value: "Asia/Tehran" },
  { label: "Asia/Baku", value: "Asia/Baku" },
  { label: "Asia/Kabul", value: "Asia/Kabul" },
  { label: "Asia/Karachi", value: "Asia/Karachi" },
  { label: "Asia/Kolkata", value: "Asia/Kolkata" },
  { label: "Asia/Kathmandu", value: "Asia/Kathmandu" },
  { label: "Asia/Dhaka", value: "Asia/Dhaka" },
  { label: "Indian/Cocos", value: "Indian/Cocos" },
  { label: "Asia/Bangkok", value: "Asia/Bangkok" },
  { label: "Asia/Shanghai", value: "Asia/Shanghai" },
  { label: "Australia/Eucla", value: "Australia/Eucla" },
  { label: "Asia/Tokyo", value: "Asia/Tokyo" },
  { label: "Australia/Darwin", value: "Australia/Darwin" },
  { label: "Australia/Sydney", value: "Australia/Sydney" },
  { label: "Australia/Lord_Howe", value: "Australia/Lord_Howe" },
  { label: "Pacific/Guadalcanal", value: "Pacific/Guadalcanal" },
  { label: "Pacific/Noumea", value: "Pacific/Noumea" },
  { label: "Pacific/Fiji", value: "Pacific/Fiji" },
  { label: "Pacific/Chatham", value: "Pacific/Chatham" },
  { label: "Pacific/Tongatapu", value: "Pacific/Tongatapu" },
  { label: "Pacific/Kiritimati", value: "Pacific/Kiritimati" },
];
